package constbase

const (
	YES = 1
	NO = 0

	// 收入
	INCOME = 1
	// 支出
	EXPENDITURE = 2

	// 其他
	STATUS_ORDER = 0
	// 佣金未到账
	STATUS_COMMISSION_NOT_ARRIVED = 1
	// 佣金已到账
	STATUS_COMMISSION_ARRIVED = 2
	// 提现未到账
	STATUS_WITHDRAW_NOT_ARRIVED = 3
	// 提现已到账
	STATUS_WITHDRAW_ARRIVED = 4

	PLAN = "plan"

	PROP_TYPE_GOLD = "gold"
	PROP_TYPE_DIAMOND = "diamond"
	PROP_TYPE_BULLET_ENHANCER = "bullet_enhancer"
	PROP_TYPE_BULLET_SPEED_ENHANCER = "bullet_speed_enhancer"
	PROP_TYPE_BULLET_RATE_ENHANCER = "bullet_rate_enhancer"
	PROP_TYPE_SKILL_ENHANCER = "skill_enhancer"
	PROP_TYPE_SKILL_SPEED_ENHANCER = "skill_speed_enhancer"
	PROP_TYPE_SKILL_RATE_ENHANCER = "skill_rate_enhancer"

	SHARE_POSITION_MENU = "menu"
	SHARE_POSITION_INDEX_BUTTON = "index_button"

	ENHANCER_SUCCESS = "success"
	ENHANCER_FAIL = "fail"

	// 530 ~ 540 是 websocket 专用码
	// 服务端要求客户端关闭连接
	WEBSOCKET_CLOSE = 530
	// 被踢下线
	WEBSOCKET_OFFLINE = 531

	// websocket 接收信息类型
	WEBSOCKET_MESSAGE_TYPE_TEXT = 1
	WEBSOCKET_MESSAGE_TYPE_BINARY = 2
	WEBSOCKET_MESSAGE_TYPE_CLOSE = 8
	WEBSOCKET_MESSAGE_TYPE_PING = 9
	WEBSOCKET_MESSAGE_TYPE_PONG = 10

	// 忽略提示
	IGNORE = 201

	//登录失败
	LOGIN_FAIL = 227
	//登录成功
	LOGIN_SUCCESS = 228

	// 登录用户信息详情
	LOGIN_USER_INFO = 229
	// 强化成功
	ENHANCER_RESULT = 230
	// 刷副本奖励
	LEVEL_PASS_PRIZE = 231
	// 关卡详情
	LEVEL_INFO = 232
	// 签到成功
	SIGN_IN_SUCCESS = 234
	SIGN_IN_FAIL = 235
	// 更换飞机
	USER_PLAN_CHANGE_SUCCESS = 236
	USER_PLAN_CHANGE_FAIL = 237
	// 背包列表
	BACKPACK_LIST = 238


	// 商店列表
	STORE_LIST = 239
	// 商店道具兑换
	STORE_BUY_SUCCESS = 240

	BACKPACK_SELL_SUCCESS = 241
	BACKPACK_SELL_FAIL = 242

	// 升级成功
	USER_PLAN_UPGRADE_SUCCESS = 243

	CHAT_MESSAGE = 290
)
